Implement listing all load balancers
eBay/go-ovn pull request #141
Opened 2021-03-22 08:12 UTC by palanik1

This PR adds functionality for listing all Load Balancers

Co-authored by : Sayandeep Sen sayandes@in.ibm.com

Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>

2021-03-22 20:38 UTC, vtolstov requested changes
after gofmt will be merged

2021-03-22 20:38 UTC, vtolstov commented on load_balancer.go
> +		if(err != nil){
needs gofmt, please gofmt all files

2021-03-23 05:17 UTC, palanik1 commented on load_balancer.go
> +		if(err != nil){
Done.

2021-03-23 05:23 UTC, palanik1 commented
@vtolstov Addressed your comments. Please take a look. Thanks.

2021-03-23 05:26 UTC, vtolstov approved these changes

2021-03-23 05:26 UTC, merged

2021-03-23 05:26 UTC, vtolstov commented
merged as it simple change

2021-03-23 05:27 UTC, palanik1 commented
@vtolstov Thank you for your reviews and quick response.